// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8BOPT2LZr7QOuE_AXs3iCNt96zo1Zs0',
    appId: '1:655493523402:web:298eb9f9e6db5de4521133',
    messagingSenderId: '655493523402',
    projectId: 'kos-hub-app',
    authDomain: 'kos-hub-app.firebaseapp.com',
    storageBucket: 'kos-hub-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3NJBdEmnl5pijs3iA-OPMXB7N1-zA8Cg',
    appId: '1:655493523402:android:4f63c6e53da8203a521133',
    messagingSenderId: '655493523402',
    projectId: 'kos-hub-app',
    storageBucket: 'kos-hub-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbTX0jFcXvSspnRIHOPI9qLetoPCokfyw',
    appId: '1:655493523402:ios:4a748f3b4225d45b521133',
    messagingSenderId: '655493523402',
    projectId: 'kos-hub-app',
    storageBucket: 'kos-hub-app.firebasestorage.app',
    iosBundleId: 'com.example.kosHub',
  );
}
